### ISSUE TITLE
Dev data errors

### ISSUE THREAD

**Issue by jerbarnes** [ltgoslo/NoMusic#1]
Dear organizers,

First off, thanks for setting up this shared task. I was having a look at the data and realized that the dev data has a few errors:

id = 289/1: no text, I imagine it should be removed
id = 253/10: token 5 is lacking the slot tag (presumably 'O')

Best,
Jeremy

**Comment by yvesscherrer** [comment]
Thanks for spotting these mistakes and sorry for the late reply, I didn't get notified. We fixed 253/10, but decided to leave 289/1 as it is in order not to change the order of examples in the dev set. But feel free to ignore this example.
